CREATE TABLE ORDERS
(
  ID INTEGER NOT NULL,
  PRODUCT_ID INTEGER NOT NULL,
  CLIENT_ID INTEGER NOT NULL,
  QUANTITY INTEGER NOT NULL,
  AMOUNT DECIMAL NOT NULL,
  TAXES DECIMAL NOT NULL,
  TOTAL_AMOUNT DECIMAL NOT NULL,
  STATE VARCHAR(150) NOT NULL,
  ORDER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_ORDER PRIMARY KEY(ID)
);

CREATE TABLE ORDER_DETAILS
(
  ID INTEGER NOT NULL,
  ORDER_ID INTEGER NOT NULL,
  DESCRIPTION VARCHAR(100) NOT NULL,
  DETAIL_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_ORDER_DETAILS PRIMARY KEY(ID),
  CONSTRAINT FK_ORDER_ORDER_DETAILS FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID)
);